### PR TITLE
Add playground

### PR DESCRIPTION
**Pull request by koxudaxi**
I copied files from my [tagstr-playground](https://github.com/koxudaxi/tagstr-playground) 

### Checkpoint
- Should we update the license and README?
 I don't have any ideas or requests. I just copied the original files.
- Setup GitHub pages to deploy the site
  The PR uses the actions https://github.com/actions/deploy-pages
### Related Issues
https://github.com/pauleveritt/tagstr-site/issues/2

### CODE REVIEW

**Comment by pauleveritt** [comment]
I propose the following:

- Let's put the MIT license file at the root of the repo, thus it applies to everything. We will put all of our names in it.
- I will take the contents of your README and add it to the README at the top.

**Comment by pauleveritt** [comment]
I think you forgot to commit the `greet.ipynb` file?

EDIT: I read your followup email where you said we can add whatever notebooks we want.

**Comment by pauleveritt** [comment]
What's the best way to run your JupyterLite setup locally, with the notebook that we'll be shipping?

**Comment by pauleveritt** [comment]
I believe your `pyproject.toml` was written just for use by GitHub Actions. But for local execution, perhaps we should get this line working also in our top-level `pyproject.toml` ? 

`poetry run jupyter lite build --contents content --output-dir dist`

Meaning, add whatever dependencies are needed. Should be pretty easy.

**Comment by koxudaxi** [comment]
> I think you forgot to commit the greet.ipynb file?

https://github.com/koxudaxi/tagstr-playground/pull/3/files

I'm sorry that I forgot to share my experimental PR for you.
I will commit the notebook files as other PRs after we decide what we should write as notebooks.

> What's the best way to run your JupyterLite setup locally, with the notebook that we'll be shipping?

OK, I will add the step as Makefile.

**Comment by koxudaxi** [comment]
@pauleveritt 
I just updated the PR.
1. Moved the LICENSE file to the top level of the repo.
2. Migrated Poetry to existing `pyproject.toml` on the repo.
3. Move the build task to `Makefile`
4. GitHub actions task uses Makefile to build `playground site`

**Comment by koxudaxi** [comment]
I tested only Makefile to build the playground. 
We should test the GitHub actions.

**Comment by pauleveritt** [comment]
Do you think we should merge now, or wait until we have updates for 3.14? IMO, we can go ahead and merge now. The JupyterLite stuff is useful even with the 3.12-based branch.

**Comment by koxudaxi** [comment]
I want to merge it now. It's to avoid conflict in another branch.

**Pull request merged**
