### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by koxudaxi**
@pauleveritt 
I copied only the Dockerfiles from my repo. https://github.com/koxudaxi/tagstr-docker

I have two questions.
1. Should I add the Makefile and git submodule-config in the repo? 
We need the files if the CPython tagstr branch is updated.
2. Should I add my docker registry URL, image name, and tag in README? https://hub.docker.com/r/koxudaxi/python
 But your name or another organization might be more trustworthy.
 I think it would be better to publish it in a registry somewhere since it would take quite a long time to build it.
 3. Should I add [GitHub action to publish](https://github.com/koxudaxi/tagstr-docker/blob/main/.github/workflows/publish.yml) the Docker image to the registry? 
 I think it is important to clearly show that it was published in accordance with the published flow to appeal to transparency.

### CODE REVIEW

**Comment by pauleveritt** [comment]
1. We can add the Makefile, sure. For git submodule-config, that's your decision.
2. Let's keep your docker registry URL as it is. In six months, either this will be in Python or it will be abandoned. :)
3. Would the GHA trigger a Docker image build on every merge? If so: no, let's build and upload images by hand, outside of GHA.

**Comment by pauleveritt** [comment]
@koxudaxi Are you still ok with (2) above...editing the README to point to the builds you have in your Docker registry?

**Comment by koxudaxi** [comment]
@pauleveritt 
I'm sorry, I got home early in the morning and suffered from jet lag.

> @koxudaxi Are you still ok with (2) above...editing the README to point to the builds you have in your Docker registry?

Of course, we can use the registry. The badge "Sponsored OSS" is updated for 1 year. So, we can use pull without limitation

**Comment by pauleveritt** [comment]
I added a section to the README.

**Pull request merged**
